sqlite:
  provider: sqlite
  filename: organisation.db
  create_db: true
mysql:
  provider: mysql
  host: '#'
  user: '#'
  passwd: '#'
  db: '#'
postgres:
  provider: postgres
  user: '#'
  password: '#'
  host: '#'
  database: '#'
oracle:
  provider: oracle
  user: '#'
  password: '#'
  dsn: '#'
